version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"  # Expose le port 27017 pour accéder à MongoDB depuis l'extérieur
    volumes:
      - mongo_data:/data/db  # Persiste les données de MongoDB
    networks:
      - app-network  # Connecte MongoDB au réseau d'application

  spring-app:
    build:
      context: .  # Utilise le Dockerfile dans le répertoire courant
      dockerfile: ./Dockerfile
    container_name: spring_app_container
    ports:
      - "8080:8080"  # Expose le port 8080 pour accéder à l'application Spring
    depends_on:
      - mongodb  # Assure que MongoDB est démarré avant l'application Spring
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/service_social_db  # URI de connexion à MongoDB
    networks:
      - app-network  # Connecte l'application Spring au réseau d'application

volumes:
  mongo_data:  # Déclare un volume pour persister les données de MongoDB

networks:
  app-network:  # Déclare un réseau pour les services
